name: "Compiler CI"

on:
  push:
    paths:
      - "ohdlc/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "ohdlc/**"
      - ".github/workflows/**"
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: "[Compiler] Cargo Build & Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    defaults:
      run:
        working-directory: ohdlc
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
